import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, test } from "vitest";

/**
 * NO DATA FILE MAY BEGIN WITH A BYTE ORDER MARK.
 *
 * ⚠ THIS IS A PRECONDITION FOR C#↔TS PARITY, not tidiness. `String.prototype.trim` and .NET's
 * `string.Trim()` disagree about exactly two characters: JS strips U+FEFF and .NET does NOT, while .NET
 * strips U+0085 and JS does not. The Wu port found the live half of that gap — a BOM-prefixed Wugniu
 * reading took the romanization path in Node and the ENGLISH FOREIGN READER in .NET — and `Core/Js.cs`
 * now carries a `Js.Trim` shim for text that flows through the engine.
 *
 * ⚠ BUT 23 `.Trim()` CALL SITES REMAIN IN THE C# TREE, and roughly half of them are DATA LOADERS —
 * `LoadTsv`, the Afrikaans and Dutch morphology line readers, `Core/Segment.cs`, the English dictionary,
 * the Arabic diacritizer's line scan. Those were audited and are safe, and they are safe FOR ONE REASON:
 * no file they read starts with a BOM. If one ever did, JS would strip it from the first key and .NET
 * would keep it, and a single lexicon entry would go missing in C# alone — invisible to the parity gate
 * unless a golden row happened to use that exact first headword.
 *
 * Auditing the call sites proved they agree TODAY. This test is what keeps the premise true tomorrow, and
 * it is the cheaper half: one assertion over the tree beats re-deriving 23 sites whenever a data file is
 * regenerated by a tool that helpfully adds a BOM.
 *
 * Measured when written: 280 data files, 0 with a BOM. A cross-engine differential over 86 gated
 * languages × 8 BOM/NEL-bearing probes was byte-identical in the IPA column.
 */
const DATA = "data";
const EXTS = [".tsv", ".jsonc", ".txt", ".json"];

function walk(dir: string, out: string[] = []): string[] {
    for (const e of readdirSync(dir)) {
        const p = join(dir, e);
        if (statSync(p).isDirectory()) walk(p, out);
        else if (EXTS.some((x) => p.endsWith(x))) out.push(p);
    }
    return out;
}

describe("data files carry no BOM — the precondition the C# loaders' .Trim() relies on", () => {
    test("no .tsv/.jsonc/.txt/.json under data/ begins with U+FEFF", () => {
        const files = walk(DATA);
        expect(files.length).toBeGreaterThan(200); // the walk actually found the tree
        const withBom = files.filter((f) => readFileSync(f, "utf8").charCodeAt(0) === 0xfeff);
        expect(withBom, `BOM would survive .NET's Trim() but not JS's: ${withBom.join(", ")}`).toEqual([]);
    });
});
