/**
 * Build `en-syllabic.tsv` — which schwa+sonorant slots of a dictionary word are SYLLABIC.
 *
 * ⚠ WHY A SEPARATE FILE AND NOT THE DICT. `g2p-dict.tsv` is REGENERATED from upstream CMUdict by
 * `en_g2p_ngram.ts --emit`, which silently reverts hand edits — that is what `g2p-curated.tsv`
 * exists to record. CMUdict does not mark syllabicity (`able` and `normal` are both `AH0 L`), so
 * the marks cannot live there and survive. They live here, keyed by word, and the converter
 * consults them.
 *
 * ⚠ WHY misaki AND NOT A REFEREE. There is no derivable rule: the best ARPABET context (`AH0 L`
 * word-final) is only 76% syllabic and every other context is a coin flip. And there is no
 * independent oracle — the one shipped English referee (wikipron, human) marks a syllabic
 * consonant on 60 of 4,558 rows, and on the 35 also in misaki's gold the two agree 66%, disagreeing
 * SYSTEMATICALLY on `-tion` (`ʃn̩` vs `ʃən`) and `-ism` (`zm̩` vs `zəm`).
 *
 * That disagreement is the point: whether `-tion` is written syllabic or schwa+n is a TRANSCRIPTION
 * CONVENTION, not a fact about the sound. Kokoro learned misaki's convention, so matching it is
 * copying it — no rule and no second opinion can reconstruct an arbitrary choice. This file is
 * therefore openly a convention import, not a derivation.
 *
 * SOURCE: misaki `us_gold.json` (hexgrad/misaki, Apache-2.0). Only the SLOT POSITIONS are taken —
 * no phoneme strings — and only for words our own dictionary already has.
 *
 *   npx tsx tools/english/en_build_syllabic.mts <path-to-us_gold.json>          verify
 *   npx tsx tools/english/en_build_syllabic.mts <path-to-us_gold.json> --write  write the table
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DATA = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "data", "languages", "english");
const goldPath = process.argv[2];
const write = process.argv.includes("--write");
if (!goldPath) { console.error("usage: en_build_syllabic.mts <us_gold.json> [--write]"); process.exit(2); }

const gold = JSON.parse(readFileSync(goldPath, "utf8")) as Record<string, unknown>;
const dict = new Map<string, string[]>();
for (const line of readFileSync(join(DATA, "g2p-dict.tsv"), "utf8").split("\n")) {
    const tab = line.indexOf("\t");
    if (tab <= 0) continue;
    dict.set(line.slice(0, tab), line.slice(tab + 1).trim().split(" "));
}

const SON: Record<string, string> = { L: "l", N: "n", M: "m" };
const stats = new Map<string, number>();
const bump = (k: string) => stats.set(k, (stats.get(k) ?? 0) + 1);
const out = new Map<string, number[]>();

for (const [wRaw, gRaw] of Object.entries(gold)) {
    if (typeof gRaw !== "string" || !gRaw.includes("ᵊ")) continue;
    const w = wRaw.toLowerCase();
    const P = dict.get(w);
    if (!P) { bump("not in our dictionary"); continue; }

    // Align by SONORANT INDEX, not by counting marks: `abdominal` has two AH0+sonorant slots and one
    // mark, and only the position says which. The k-th ARPABET sonorant is the k-th gold sonorant.
    const arp: number[] = [];
    for (let i = 0; i < P.length; i++) if (P[i]! in SON) arp.push(i);
    const gs: number[] = [];
    for (let j = 0; j < gRaw.length; j++) if ("lnm".includes(gRaw[j]!)) gs.push(j);
    if (arp.length !== gs.length) { bump("sonorant count mismatch"); continue; }
    if (arp.some((i, k) => SON[P[i]!] !== gRaw[gs[k]!])) { bump("sonorant identity mismatch"); continue; }

    const slots: number[] = [];
    for (let k = 0; k < arp.length; k++) {
        const j = gs[k]!;
        if (j > 0 && gRaw[j - 1] === "ᵊ") {
            const v = arp[k]! - 1;
            if (v >= 0 && (P[v] === "AH0" || P[v] === "IH0")) slots.push(v);
            else bump("mark with no AH0/IH0 slot before it");
        }
    }
    if (slots.length) { out.set(w, [...new Set(slots)].sort((a, b) => a - b)); bump("aligned"); }
    else bump("marks present but none aligned");
}

for (const [k, v] of [...stats].sort((a, b) => b[1] - a[1])) console.log(`${String(v).padStart(7)}  ${k}`);
console.log(`\nwords: ${out.size}   slots: ${[...out.values()].reduce((n, v) => n + v.length, 0)}`);

if (write) {
    const header = [
        "# SYLLABIC CONSONANT SLOTS — which AH0/IH0 before an L/N/M is a SYLLABIC consonant, not a schwa.",
        "#",
        "# Generated by tools/english/en_build_syllabic.mts. See that file for why this is a separate",
        "# table (g2p-dict.tsv is regenerated from upstream CMUdict and would revert it), and why the",
        "# source is misaki rather than a referee (no derivable rule, and no independent oracle).",
        "#",
        "# SOURCE: misaki us_gold.json (hexgrad/misaki, Apache-2.0) — slot POSITIONS only, for words",
        "# our own dictionary already has. See en-syllabic.PROVENANCE.md.",
        "#",
        "# word <TAB> comma-separated indices into the g2p-dict.tsv ARPABET row",
    ].join("\n");
    const body = [...out].sort(([a], [b]) => (a < b ? -1 : 1)).map(([w, s]) => `${w}\t${s.join(",")}`).join("\n");
    writeFileSync(join(DATA, "en-syllabic.tsv"), `${header}\n${body}\n`, "utf8");
    console.log(`\nwrote ${join(DATA, "en-syllabic.tsv")}`);
}
