// Parity runner — the port's definition of done.
//
// ⚠ THE GOLDENS ARE ASYNC-MODE OUTPUT. tools/gen_parity_goldens.mts calls phonemizeAsync, which loads
// the ONNX neural taggers; the sync phonemize() falls back to rule g2p and produces DIFFERENT IPA for
// every neural language (af, bn, ckb, da, en, fr, he, km, nb, fa...). Measured: comparing goldens
// against sync output showed 467 of 2,400 rows "changed" — none of them real. Whatever entry point
// this runner calls MUST be the neural-capable one, or the gate reports hundreds of phantom failures
// and the real ones drown in them.
//
// ⚠ BYTE-IDENTICAL OR IT IS NOT PORTED. Reads csharp/goldens/<code>.tsv (text \t expected-ipa,
// generated by tools/gen_parity_goldens.mts from the TypeScript engine), runs the C# engine on the
// same text, and diffs. "Close" is not a state: a one-codepoint drift in one language is a porting
// bug with a locale, a regex dialect, or an ordering assumption behind it, and those never stay
// confined to the row that exposed them.
//
//   dotnet run --project csharp/tools/parity            all goldens
//   dotnet run --project csharp/tools/parity -- fr th   just these codes
using System.Text;
using Vernacula.Phonemizer;
using Vernacula.Phonemizer.Core;

var goldens = Path.Combine(AppContext.BaseDirectory, "../../../../../goldens");
if (!Directory.Exists(goldens)) goldens = "csharp/goldens";
var only = args.Where(a => !a.StartsWith('-')).ToHashSet();
int langsOk = 0, langsBad = 0, rowsOk = 0, rowsBad = 0;
var firstDiff = new List<string>();
var dependencyGaps = new SortedSet<string>(StringComparer.Ordinal);

foreach (var file in Directory.EnumerateFiles(goldens, "*.tsv").OrderBy(f => f, StringComparer.Ordinal))
{
    var code = Path.GetFileNameWithoutExtension(file);
    if (only.Count > 0 && !only.Contains(code)) continue;
    int ok = 0, bad = 0;
    string? sample = null;
    // ⚠ SNAPSHOT PER LANGUAGE, not once for the run. Every UNPORTED golden also asks the registry for its own
    // engine, so a run-wide list named all 105 of them and buried the two entries that matter — the engines a
    // PORTED language reached through the script router and did not get.
    var pendingBefore = Registry.PortPending.ToHashSet(StringComparer.Ordinal);
    // ⚠ AND THE FOREIGN-OOV MEMO IS CLEARED PER LANGUAGE, for the same reason the GENERATOR clears it: it is
    // global, so a mixed-script language's prewarm would otherwise leave BiLSTM readings that a later
    // Latin-script language picks up through the foreign reader — making a row pass because of what ran
    // before it. The goldens are generated per-language-isolated; the gate has to measure the same way.
    Foreign.ClearForeignOov();
    foreach (var line in File.ReadLines(file))
    {
        var t = line.Split('\t');
        if (t.Length != 2) continue;
        string got;
        // ⚠ THE NEURAL-CAPABLE ENTRY, per the async-goldens warning above. Calling the sync Phonemize here
        // reported the ENGINE as broken for every neural language: af showed 120/200 rows differing, all of
        // them the rule g2p standing in for the tagger.
        try { got = Phonemizer.PhonemizeAsync(t[0], code).GetAwaiter().GetResult(); }
        catch (NotImplementedException) { goto notPorted; }
        catch (Exception e) { got = $"<THREW {e.GetType().Name}: {e.Message}>"; }
        if (got == t[1]) ok++;
        else { bad++; sample ??= $"  {code}: \"{t[0][..Math.Min(48, t[0].Length)]}\"\n    want {t[1]}\n    got  {got}"; }
    }
    rowsOk += ok; rowsBad += bad;
    foreach (var key in Registry.PortPending) if (!pendingBefore.Contains(key)) dependencyGaps.Add($"{code} → {key}");
    if (bad == 0) { langsOk++; Console.WriteLine($"  {code,-8} OK    {ok} rows"); }
    else { langsBad++; Console.WriteLine($"  {code,-8} DIFF  {bad}/{ok + bad} rows differ"); if (firstDiff.Count < 8 && sample != null) firstDiff.Add(sample); }
    continue;
notPorted:
    Console.WriteLine($"  {code,-8} not ported");
}
Console.WriteLine($"\n{langsOk} languages byte-identical, {langsBad} differ ({rowsOk} rows ok, {rowsBad} differ)");
// ⚠ A DIFF MAY NOT BE A PORTING BUG. The script router reads an embedded foreign run through ANOTHER
// language's engine and catches the failure, so an unported target silently drops the run and the row
// just differs. Naming the keys that were asked for and missing separates "blocked" from "wrong".
if (dependencyGaps.Count > 0)
    Console.WriteLine("⚠ a PORTED language reached for an engine that is not ported (its rows cannot pass yet): "
                      + string.Join(", ", dependencyGaps));
foreach (var d in firstDiff) Console.WriteLine(d);

// ─── ACCENT-VARIANT CENSUS ─────────────────────────────────────────────────────────────────────────
//
// ⚠ THE LOOP ABOVE ITERATES GOLDEN FILES, SO A CODE WITH NO GOLDEN IS INVISIBLE TO IT. That is not a
// gap for an unported LANGUAGE — those are tracked by the porting queue and their absence is expected.
// It is a gap for an accent VARIANT of a language that IS ported, because the base shows green and a
// reader reasonably concludes the locale works. `es-419` sat in exactly that state: `Registry.Build`
// has carried `case "es-419": return Create("spanish-419")` since the switch was mirrored from the
// TypeScript, nothing ever registered that factory, every call threw `port pending: spanish-419`, and
// the gate said "55 languages byte-identical" without a word about it.
//
// So the variants are named explicitly and BUILT, whether or not they have a golden. An explicit list
// is the same call Languages/Bootstrap.cs makes and for the same reason: five entries in one place
// beats the answer being spread across the registry switch, and "which variants exist?" stays one grep.
// A variant that gains a golden is checked by the loop above as well; this only answers "does it exist".
var variants = new (string Code, string Base)[]
{
    ("en-GB", "en"), ("en-IN", "en"), ("es-419", "es"), ("fr-CA", "fr"), ("pt-BR", "pt"),
};
var variantPending = new List<string>();
var variantOk = new List<string>();
foreach (var (code, baseCode) in variants)
{
    try { Phonemizer.Phonemize("1", code); variantOk.Add(code); }
    catch (NotImplementedException) { variantPending.Add($"{code} (variant of {baseCode})"); }
    catch { variantOk.Add(code); } // it built; a render failure is the loop above's business, not this census
}
Console.WriteLine($"\naccent variants: {variantOk.Count}/{variants.Length} build"
                  + (variantOk.Count > 0 ? $" — {string.Join(", ", variantOk)}" : ""));
if (variantPending.Count > 0)
    Console.WriteLine("⚠ NOT PORTED, and their base language IS: " + string.Join(", ", variantPending));

return langsBad == 0 ? 0 : 1;
