// Parity runner — the port's definition of done.
//
// ⚠ THE GOLDENS ARE ASYNC-MODE OUTPUT. tools/gen_parity_goldens.mts calls phonemizeAsync, which loads
// the ONNX neural taggers; the sync phonemize() falls back to rule g2p and produces DIFFERENT IPA for
// every neural language (af, bn, ckb, da, en, fr, he, km, nb, fa...). Measured: comparing goldens
// against sync output showed 467 of 2,400 rows "changed" — none of them real. Whatever entry point
// this runner calls MUST be the neural-capable one, or the gate reports hundreds of phantom failures
// and the real ones drown in them.
//
// ⚠ BYTE-IDENTICAL OR IT IS NOT PORTED. Reads csharp/goldens/<code>.tsv (text \t expected-ipa,
// generated by tools/gen_parity_goldens.mts from the TypeScript engine), runs the C# engine on the
// same text, and diffs. "Close" is not a state: a one-codepoint drift in one language is a porting
// bug with a locale, a regex dialect, or an ordering assumption behind it, and those never stay
// confined to the row that exposed them.
//
//   dotnet run --project csharp/tools/parity            all goldens
//   dotnet run --project csharp/tools/parity -- fr th   just these codes
//   dotnet run --project csharp/tools/parity -- --unported   which codes have no C# engine
using System.Text;
using Vernacula.Phonemizer;
using Vernacula.Phonemizer.Core;

var goldens = Path.Combine(AppContext.BaseDirectory, "../../../../../goldens");
if (!Directory.Exists(goldens)) goldens = "csharp/goldens";
var only = args.Where(a => !a.StartsWith('-')).ToHashSet();

/*
 * `--poison`: WHERE the mapping dies, by call site. The C# mirror of `tools/provenance-poison.mts`.
 *
 * ⚠ THE SEAM'S RULE CANNOT BE CHECKED STATICALLY. `s = Rewrite(s, RE, rep)` inside a per-word helper is
 * textually identical to the pipeline form; only running the corpus and asking who handed the seam an
 * unrecognised string tells them apart. Needs a Debug build for line numbers.
 */
/*
 * `--unported`: WHICH registry codes have no C# engine. Asked of the ENGINE — every code `Registry.cs`
 * routes is created and the port-pending ones reported — rather than read off a hand-kept list, because a
 * hand-kept list is exactly what `csharp/STATUS.md` was and exactly how it went stale (it said 136 of 193
 * at a point when the number was already higher).
 *
 * ⚠ AND IT IS NOT REDUNDANT WITH `parity | grep "not ported"`, WHICH WAS THE OBVIOUS OBJECTION AND WAS
 * MEASURED. The main loop is GOLDEN-DRIVEN (`EnumerateFiles(goldens, "*.tsv")`), so a code with no golden
 * is never visited and never prints:
 *     grep "not ported"   21 codes, after a full ~2-minute gate run over 31,964 rows
 *     --unported          26 codes, in seconds
 * The five it cannot see — mto naq nog quc smj — are exactly the ones that CANNOT be ported yet, because a
 * language with nothing to be byte-identical to has no gate. Those are the most useful rows in the list,
 * which is why the flag also reports each code's engine and whether a golden exists at all.
 *
 * ⚠ THE CODES COME FROM `Registry.cs`'s OWN `case` LABELS. The registry has no enumeration export, and
 * duplicating one here would reintroduce the drift this flag exists to remove.
 *
 *   dotnet run --project csharp/tools/parity -- --unported
 */
if (args.Contains("--unported"))
{
    var registrySrc = Path.Combine(AppContext.BaseDirectory, "../../../../../Vernacula.Phonemizer/Registry.cs");
    if (!File.Exists(registrySrc)) registrySrc = "csharp/Vernacula.Phonemizer/Registry.cs";
    var codes = JsRegex.Compile("^\\s*case \"([^\"]+)\":", "gmu")
        .Matches(File.ReadAllText(registrySrc))
        .Select(m => m.Groups[1].Value).Distinct(StringComparer.Ordinal)
        .OrderBy(c => c, StringComparer.Ordinal).ToList();
    // ⚠ CATCH THE TYPE, NOT THE MESSAGE. `Registry.Create` throws `NotImplementedException("port pending:
    // <key>")` and the row loop below catches `NotImplementedException` — matching that is what keeps this
    // flag honest. A `Message.Contains("port pending")` test reads the same today and reports ZERO UNPORTED,
    // silently and greenly, the day anyone rewords the string.
    // ⚠ AND `ClearPortPending` PER CODE, for the reason the row loop states: the set is process-wide and
    // only grows, so without this every later code inherits the first unported one's key.
    var pending = new List<(string Code, string Engine)>();
    foreach (var code in codes)
    {
        Registry.ClearPortPending();
        try { Phonemizer.Phonemize("a", code); }
        catch (NotImplementedException)
        {
            // The registry records WHICH engine it was asked for, which is the useful half: several codes
            // route to one engine (`gd` → scottishgaelic), so the engine count is what the port queue is.
            pending.Add((code, Registry.PortPending.FirstOrDefault() ?? "?"));
        }
        catch { /* any other refusal is a different question */ }
    }
    var engines = pending.Select(p => p.Engine).Where(e => e != "?").Distinct(StringComparer.Ordinal).ToList();
    Console.WriteLine($"{codes.Count} codes routed by Registry.cs · {codes.Count - pending.Count} ported · {pending.Count} UNPORTED ({engines.Count} distinct engines)");
    Console.WriteLine(string.Join(" ", pending.Select(p => p.Code)));
    Console.WriteLine("\n(a golden is what makes one gateable: csharp/goldens/<code>.tsv)");
    foreach (var (c, engine) in pending)
    {
        var g = Path.Combine(goldens, c + ".tsv");
        Console.WriteLine($"  {c,-5} → {engine,-18} {(File.Exists(g) ? $"golden {File.ReadLines(g).Count()} rows" : "NO GOLDEN — needs tools/gen_parity_goldens.mts first")}");
    }
    return 0;
}

if (args.Contains("--poison"))
{
    var hits = new Dictionary<string, (int N, string Kind, string Sample)>(StringComparer.Ordinal);
    Provenance.OnPoison((expected, got) =>
    {
        var frames = new System.Diagnostics.StackTrace(true).GetFrames()
            .Select(fr => (File: fr.GetFileName(), Line: fr.GetFileLineNumber(), Method: fr.GetMethod()?.Name))
            .Where(fr => fr.File is not null && !fr.File.Contains("Provenance.cs") && !fr.File.Contains("Rewriter.cs"))
            .Take(3)
            // ⚠ THE BARE FILE NAME IS USELESS HERE — every language has a `Normalize.cs`, so 114 distinct
            // sites collapse onto one label. Keep enough of the path to name the language.
            .Select(fr => $"{Rel(fr.File!)}:{fr.Line} {fr.Method}");
        var key = string.Join("  <- ", frames);
        var kind = (expected.Contains(got, StringComparison.Ordinal) && got.Length < expected.Length)
            || got.Length * 3 < expected.Length ? "SUBSTRING" : "desync";
        if (hits.TryGetValue(key, out var cur))
            hits[key] = (cur.N + 1, cur.Kind == kind ? kind : "mixed", cur.Sample);
        else
            hits[key] = (1, kind, $"tracked={Truncate(expected)} s={Truncate(got)}");
    });
    static string Truncate(string x) => x.Length <= 40 ? x : x[..40];
    static string Rel(string f)
    {
        var i = f.IndexOf("Vernacula.Phonemizer/", StringComparison.Ordinal);
        return i < 0 ? Path.GetFileName(f) : f[(i + "Vernacula.Phonemizer/".Length)..];
    }
    foreach (var f in Directory.EnumerateFiles(goldens, "*.tsv").OrderBy(x => x, StringComparer.Ordinal))
    {
        var lang = Path.GetFileNameWithoutExtension(f);
        if (only.Count > 0 && !only.Contains(lang)) continue;
        foreach (var line in File.ReadLines(f))
        {
            var text = line.Split('\t')[0];
            if (text.Length == 0) continue;
            try { Phonemizer.PhonemizeTrace(text, lang); } catch { /* the reading is gated elsewhere */ }
        }
    }
    Provenance.OnPoison(null);
    var subs = hits.Where(h => h.Value.Kind != "desync").ToList();
    Console.WriteLine($"distinct poison sites: {hits.Count}  (SUBSTRING {subs.Count}, desync {hits.Count - subs.Count})");
    Console.WriteLine("\n=== SUBSTRING — revert these to JsRe.Replace ===");
    foreach (var h in subs.OrderByDescending(x => x.Value.N)) Console.WriteLine($"{h.Value.N,6} {h.Value.Kind,-9} {h.Key}");
    Console.WriteLine("\n=== desync — the subject IS the pipeline string; the gap is an earlier non-Replace step ===");
    foreach (var h in hits.Where(x => x.Value.Kind == "desync").OrderByDescending(x => x.Value.N))
        Console.WriteLine($"{h.Value.N,6}  {h.Key}\n        {h.Value.Sample}");
    return 0;
}

/*
 * `--provenance`: per-language #1150 stage-2 coverage, the C# mirror of `tools/provenance-coverage.mts`.
 *
 * ⚠ A FLEET AVERAGE SAYS HOW MUCH IS MISSING AND NEVER WHERE. Ranking by tokens LOST is what turns
 * "the mapping is 95% complete" into a named next fix, and it is also the only way to see the two
 * engines diverge on one language while the totals agree — `mai`, `awa` and `mag` read ~40-60% here
 * while the TypeScript has them at 100%.
 */
/*
 * `--ipaspans`: per-language #1150 stage-3 coverage — the OUTPUT half, and the twin of
 * `tools/ipa-span-coverage.mts`.
 *
 * ⚠ THE CHECK DEPENDS ON WHETHER A POST-ASSEMBLY PASS RAN. With none, a token's `Emitted` IS a substring of
 * the reading, so containment is the strong check. After a POSITIONAL pass it is not — Spanish emits ɡˈato
 * where the sentence reads ɣˈato — and what survives is the WIDTH.
 */
if (args.Contains("--ipaspans"))
{
    var rows = new List<(string Lang, int Tok, int Mapped, int Wrong)>();
    foreach (var f in Directory.EnumerateFiles(goldens, "*.tsv").OrderBy(x => x, StringComparer.Ordinal))
    {
        var lang = Path.GetFileNameWithoutExtension(f);
        if (only.Count > 0 && !only.Contains(lang)) continue;
        int tok = 0, mapped = 0, wrong = 0;
        foreach (var line in File.ReadLines(f))
        {
            var text = line.Split('\t')[0];
            if (text.Length == 0) continue;
            PhonemeTrace t;
            try { t = Phonemizer.PhonemizeTrace(text, lang); } catch { continue; }
            var rewritten = t.Rewrites.Any(x => x.Stage != "normalize");
            foreach (var k in t.Tokens)
            {
                if (k.Emitted.Count == 0) continue;
                tok++;
                if (k.IpaSpan is null) continue;
                mapped++;
                if (k.IpaSpan.Value.End > t.Ipa.Length || k.IpaSpan.Value.Start < 0) { wrong++; continue; }
                var slice = t.Ipa[k.IpaSpan.Value.Start..k.IpaSpan.Value.End];
                var want = k.Emitted.Sum(e => e.Length) + k.Emitted.Count - 1;
                if (rewritten ? slice.Length != want : !k.Emitted.All(e => slice.Contains(e, StringComparison.Ordinal))) wrong++;
            }
        }
        if (tok > 0) rows.Add((lang, tok, mapped, wrong));
    }
    var tt = rows.Sum(r => r.Tok);
    var tm = rows.Sum(r => r.Mapped);
    Console.WriteLine($"{rows.Count} languages · tokens with IpaSpan {tm}/{tt} ({100.0 * tm / tt:F1}%)");
    Console.WriteLine($"⚠ spans that do not cover what the token emitted: {rows.Sum(r => r.Wrong)}\n");
    Console.WriteLine("lost   %mapped  wrong  lang");
    foreach (var r in rows.Where(x => x.Mapped < x.Tok || x.Wrong > 0).OrderByDescending(x => x.Tok - x.Mapped))
        Console.WriteLine($"{r.Tok - r.Mapped,5}  {100.0 * r.Mapped / r.Tok,5:F0}%  {r.Wrong,5}  {r.Lang}");
    return 0;
}

if (args.Contains("--provenance"))
{
    var report = new List<(string Lang, int Tok, int Mapped, int FullRows, int Rows)>();
    foreach (var f in Directory.EnumerateFiles(goldens, "*.tsv").OrderBy(x => x, StringComparer.Ordinal))
    {
        var lang = Path.GetFileNameWithoutExtension(f);
        if (only.Count > 0 && !only.Contains(lang)) continue;
        int tok = 0, mapped = 0, fullRows = 0, nRows = 0;
        foreach (var line in File.ReadLines(f))
        {
            var text = line.Split('\t')[0];
            if (text.Length == 0) continue;
            PhonemeTrace t;
            try { t = Phonemizer.PhonemizeTrace(text, lang); } catch { continue; }
            nRows++;
            var m = t.Tokens.Count(k => k.InputSpan is not null);
            tok += t.Tokens.Count; mapped += m;
            if (t.Tokens.Count > 0 && m == t.Tokens.Count) fullRows++;
        }
        if (tok > 0) report.Add((lang, tok, mapped, fullRows, nRows));
    }
    var tt = report.Sum(r => r.Tok);
    var tm = report.Sum(r => r.Mapped);
    Console.WriteLine($"{report.Count} languages · tokens {tm}/{tt} ({100.0 * tm / tt:F1}%)\n");
    Console.WriteLine("lost   %mapped  rows   lang");
    foreach (var r in report.Where(x => x.Mapped < x.Tok).OrderByDescending(x => x.Tok - x.Mapped))
        Console.WriteLine($"{r.Tok - r.Mapped,5}  {100.0 * r.Mapped / r.Tok,5:F0}%  {r.FullRows,3}/{r.Rows,-3}  {r.Lang}");
    return 0;
}
int langsOk = 0, langsBad = 0, langsBlocked = 0, rowsOk = 0, rowsBad = 0, rowsBlocked = 0;
var blockedRows = new List<string>();
var firstDiff = new List<string>();
var dependencyGaps = new SortedSet<string>(StringComparer.Ordinal);

foreach (var file in Directory.EnumerateFiles(goldens, "*.tsv").OrderBy(f => f, StringComparer.Ordinal))
{
    var code = Path.GetFileNameWithoutExtension(file);
    if (only.Count > 0 && !only.Contains(code)) continue;
    int ok = 0, bad = 0;
    string? sample = null;
    // ⚠ SNAPSHOT PER LANGUAGE, not once for the run. Every UNPORTED golden also asks the registry for its own
    // engine, so a run-wide list named all 105 of them and buried the two entries that matter — the engines a
    // PORTED language reached through the script router and did not get.
    var pendingBefore = Registry.PortPending.ToHashSet(StringComparer.Ordinal);
    var blocked = 0;
    var blockedOn = new SortedSet<string>(StringComparer.Ordinal);
    string? blockedSample = null;
    // ⚠ AND THE FOREIGN-OOV MEMO IS CLEARED PER LANGUAGE, for the same reason the GENERATOR clears it: it is
    // global, so a mixed-script language's prewarm would otherwise leave BiLSTM readings that a later
    // Latin-script language picks up through the foreign reader — making a row pass because of what ran
    // before it. The goldens are generated per-language-isolated; the gate has to measure the same way.
    Foreign.ClearForeignOov();
    foreach (var line in File.ReadLines(file))
    {
        var t = line.Split('\t');
        if (t.Length != 2) continue;
        // ⚠ CLEARED PER ROW — see Registry.ClearPortPending. Without this the first Hebrew row in the run
        // poisons every later row's verdict, because the set is process-wide and only grows.
        Registry.ClearPortPending();
        string got;
        // ⚠ THE NEURAL-CAPABLE ENTRY, per the async-goldens warning above. Calling the sync Phonemize here
        // reported the ENGINE as broken for every neural language: af showed 120/200 rows differing, all of
        // them the rule g2p standing in for the tagger.
        try { got = Phonemizer.PhonemizeAsync(t[0], code).GetAwaiter().GetResult(); }
        catch (NotImplementedException) { goto notPorted; }
        catch (Exception e) { got = $"<THREW {e.GetType().Name}: {e.Message}>"; }
        if (got == t[1]) { ok++; continue; }
        // ⚠ A ROW BLOCKED ON AN UNPORTED DEPENDENCY IS NOT A PORTING BUG, AND MUST NOT BE COUNTED AS ONE —
        // but it must not be waved through either. The script router hands an embedded foreign run to
        // ANOTHER language's engine; when that engine is unported the run is dropped and the row differs
        // through no fault of the language under test (syl carries one Hebrew phrase; gan carries five).
        // The test is PER ROW and evidential: this row is blocked only if phonemizing IT is what newly
        // registered a PortPending key. A blanket per-language exemption would hide a real regression in
        // any language that happens to have one blocked row.
        // ⚠ THE BLIND SPOT, STATED: a blocked row is not checked for anything ELSE. If the same row also
        // carried a genuine defect in the language under test, this would hide it. That is why blocked rows
        // are PRINTED with their text rather than merely counted — the set is tiny (1 today) and meant to
        // be read. It shrinks to nothing when the dependency is ported, which is the only correct exit.
        var rowPending = Registry.PortPending;
        if (rowPending.Count > 0)
        {
            blocked++;
            foreach (var k in rowPending) blockedOn.Add(k);
            blockedSample ??= $"  {code}: {{n}} row(s) blocked on {string.Join(", ", rowPending)} — \"{t[0][..Math.Min(44, t[0].Length)]}\"";
            continue;
        }
        bad++; sample ??= $"  {code}: \"{t[0][..Math.Min(48, t[0].Length)]}\"\n    want {t[1]}\n    got  {got}";
    }
    rowsOk += ok; rowsBad += bad; rowsBlocked += blocked;
    if (blockedSample != null) blockedRows.Add(blockedSample.Replace("{n}", blocked.ToString()));
    foreach (var key in Registry.PortPending) if (!pendingBefore.Contains(key)) dependencyGaps.Add($"{code} → {key}");
    if (bad == 0 && blocked > 0) { langsBlocked++; Console.WriteLine($"  {code,-8} OK    {ok} rows, {blocked} BLOCKED"); }
    else if (bad == 0) { langsOk++; Console.WriteLine($"  {code,-8} OK    {ok} rows"); }
    else { langsBad++; Console.WriteLine($"  {code,-8} DIFF  {bad}/{ok + bad} rows differ"); if (firstDiff.Count < 8 && sample != null) firstDiff.Add(sample); }
    continue;
notPorted:
    Console.WriteLine($"  {code,-8} not ported");
}
Console.WriteLine($"\n{langsOk} languages byte-identical, {langsBad} differ ({rowsOk} rows ok, {rowsBad} differ)"
                  + (rowsBlocked > 0 ? $"; {langsBlocked} language(s) fully match except {rowsBlocked} row(s) BLOCKED on an unported dependency" : ""));
// ⚠ BLOCKED IS NAMED, NEVER SILENT. A blocked row is excluded from `differ` because it is not this
// language's defect, but it is counted, printed, and attributed to the engine it is waiting on — so the
// number can only go down by porting that engine, not by ignoring it.
foreach (var b in blockedRows) Console.WriteLine(b);
// ⚠ A DIFF MAY NOT BE A PORTING BUG. The script router reads an embedded foreign run through ANOTHER
// language's engine and catches the failure, so an unported target silently drops the run and the row
// just differs. Naming the keys that were asked for and missing separates "blocked" from "wrong".
if (dependencyGaps.Count > 0)
    Console.WriteLine("⚠ a PORTED language reached for an engine that is not ported (its rows cannot pass yet): "
                      + string.Join(", ", dependencyGaps));
foreach (var d in firstDiff) Console.WriteLine(d);

// ─── ACCENT-VARIANT CENSUS ─────────────────────────────────────────────────────────────────────────
//
// ⚠ THE LOOP ABOVE ITERATES GOLDEN FILES, SO A CODE WITH NO GOLDEN IS INVISIBLE TO IT. That is not a
// gap for an unported LANGUAGE — those are tracked by the porting queue and their absence is expected.
// It is a gap for an accent VARIANT of a language that IS ported, because the base shows green and a
// reader reasonably concludes the locale works. `es-419` sat in exactly that state: `Registry.Build`
// has carried `case "es-419": return Create("spanish-419")` since the switch was mirrored from the
// TypeScript, nothing ever registered that factory, every call threw `port pending: spanish-419`, and
// the gate said "55 languages byte-identical" without a word about it.
//
// So the variants are named explicitly and BUILT, whether or not they have a golden. An explicit list
// is the same call Languages/Bootstrap.cs makes and for the same reason: five entries in one place
// beats the answer being spread across the registry switch, and "which variants exist?" stays one grep.
// A variant that gains a golden is checked by the loop above as well; this only answers "does it exist".
var variants = new (string Code, string Base)[]
{
    ("en-GB", "en"), ("en-IN", "en"), ("es-419", "es"), ("fr-CA", "fr"), ("pt-BR", "pt"),
};
var variantPending = new List<string>();
var variantOk = new List<string>();
foreach (var (code, baseCode) in variants)
{
    try { Phonemizer.Phonemize("1", code); variantOk.Add(code); }
    catch (NotImplementedException) { variantPending.Add($"{code} (variant of {baseCode})"); }
    catch { variantOk.Add(code); } // it built; a render failure is the loop above's business, not this census
}
Console.WriteLine($"\naccent variants: {variantOk.Count}/{variants.Length} build"
                  + (variantOk.Count > 0 ? $" — {string.Join(", ", variantOk)}" : ""));
if (variantPending.Count > 0)
    Console.WriteLine("⚠ NOT PORTED, and their base language IS: " + string.Join(", ", variantPending));

return langsBad == 0 ? 0 : 1;
