/**
 * Native Chhattisgarhi / छत्तीसगढ़ी (hne) text phonemizer — canonical IPA. Eastern Indo-Aryan
 * (Eastern-Hindi group), Devanagari. Reuses the Hindi Devanagari engine (makeNativeHindi — schwa deletion, weight
 * stress, numbers) with a Chhattisgarhi data file. Chhattisgarhi is distinguished from Hindi mostly GRAMMATICALLY.
 *
 * ⚠ "SOLE confident divergence" IS SCOPED TO THE GRAPHEME TABLES, and this docstring used to say it flatly.
 * श/ष→[s] (no /ʃ/) is the only LETTER that maps differently, but the manifest diverges twice more, both by
 * OMISSION and both observable:
 *   · `finalRules` is EMPTY where Hindi has three, so the əɦə→ɛɦɛ lowering is gone (शहर→[sˈəɦəɾ] vs Hindi
 *     [ʃˈɛɦɛɾ] — the test below pins exactly this), along with अय→ɛj and the ɪ-offglide;
 *   · Hindi's ज्ञ→ɡj postRule is absent, so ज्ञान reads [d͡ʒɲˈaːn] against Hindi's [ɡjˈaːn]. See FILED below.
 *
 * ⚠ CANNOT-VERIFY: there is NO independent phonetic referee — wikipron/kaikki have none, epitran has no hne
 * mapping. The build is instead CORROBORATED (not measured) against Hira Lal Kavyopadhyaya's 'A Grammar of the
 * Chhattisgarhi Dialect of Eastern Hindi' (1921, rev. Grierson): its inventory confirmed श/ष→[s] (no /ʃ/) and the
 * attested UDHR sample corrected an initial error — ऐ/औ are MONOPHTHONGS [ɛː]/[ɔː] as Hindi (गौरव→[ɡɔrəʋ]), NOT the
 * Bhojpuri diphthongs. A further documented feature (reduced schwa deletion) is noted but not modelled. The
 * committed anchor is a hand-adjudicated gold of the distinctive features (test/chhattisgarhi.test.ts).
 *
 * Hindi's inherited words are not merely the default here, they are the only available answer — consistent
 * with this engine being a labelled cannot-verify approximation served via the Hindi engine. Do not replace
 * them with a guess: an unsourced word is confidently wrong, where an inherited one is merely borrowed.
 *
 * ⚠ AND THE INHERITANCE IS WIDER THAN THE NORMALIZER WORDS — by three DIFFERENT mechanisms, only one of
 * which is a fallback the manifest can override:
 *   · `ordinalSuffixes`/`irregularOrdinals` ARE a real per-file fallback (`own?.x ?? MANIFEST.x` in
 *     hindi/normalize.ts). Declared here, they would win. They are not declared, so they are Hindi's.
 *   · ⚠ THE SYMBOL TIER IS NOT A FALLBACK. `makeNativeHindi` never reads `def.symbolTier` — it takes
 *     `overrides.symbols ?? SYMBOLS`, and SYMBOLS is built ONCE at hindi.ts module scope from hindi.jsonc's
 *     tier. A `symbolTier` block added to chhattisgarhi.jsonc would deserialize, pass ManifestMappingTests,
 *     and be SILENTLY IGNORED; changing a currency or unit word here means passing a `symbols` override
 *     from this file. That tier also runs BEFORE the engine's own `symbols`/`stripSymbols`, which is why
 *     ₹500 reads *pˈaː̃t͡ʃ sˈɔː ɾˈʊpjeː* (Hindi's रुपये) and NOT the bare number the manifest's
 *     `stripSymbols` comment used to claim — the same wrong claim retracted in bhojpuri.jsonc.
 *   · THE CLOCK AND UNIT WORDS ARE IN NEITHER MANIFEST: बजकर/मिनट/बजे and किमी→किलोमीटर are hardcoded in
 *     hindi/normalize.ts, so grepping hindi.jsonc for them finds nothing.
 * The 21–99 numerals ARE in this file and are byte-identical to hindi.jsonc's. All inherited, none
 * Chhattisgarhi-sourced.
 *
 * ⚠ FILED, NOT FIXED: ज्ञ reads as its literal parts, [d͡ʒɲ]. hindi.jsonc carries a corpus-measured ज्ञ→ɡj
 * rule (73/73 FLEURS hi_in rows) and scopes it to Hindi, naming Marathi and Awadhi/Bhojpuri/Magahi as
 * languages that "likely pattern with Hindi but have no corpus evidence here". Chhattisgarhi belongs in that
 * list and is not in it — so upstream did not DECIDE about hne, it did not CONSIDER hne. There is no hne
 * corpus in this repo (no FLEURS, no tools/corpus/mined/hne.jsonc, no tools/corpus/attest/hne.jsonc —
 * verified, not assumed), so the omission cannot be settled here either. ⚠ The 5 golden rows carrying d͡ʒɲ
 * are NOT evidence either way: they are Hindi words re-rendered, so that is the engine reporting on itself.
 * Fixing this would need a Chhattisgarhi source, not a Hindi analogy.
 * ⚠ AND IT IS FAMILY-WIDE, measured: hindi.jsonc is the ONLY one of the nine Devanagari manifests in the
 * fleet that carries the rule. awadhi, bhojpuri, magahi, maithili, nepali, rangpuri, marathi and this file
 * all read the ligature as its literal parts — including marathi, which hindi.jsonc's note says reads it
 * as dnya and which has no rule for that either. One decision would settle eight manifests.
 *
 * ⚠ THE 200-ROW GOLDEN (csharp/goldens/hne.tsv) IS HINDI TEXT re-rendered through this engine, generated by
 * tools/gen_variant_golden.mts from hi.tsv. It pins C#↔TS PARITY and nothing else: no row of it is attested
 * Chhattisgarhi, so it cannot corroborate a single reading. The distinctive-feature gold below is the only
 * linguistic anchor, and it is hand-adjudicated, not measured.
 */
import { makeNativeHindi, type HindiDef, type ForeignPhonemizer } from "../hindi/hindi.ts";
import { loadManifest } from "../../core/loadManifest.ts";
import { loadSharedPhonology } from "../../core/phonology.ts";

let HNE: ReturnType<typeof makeNativeHindi> | undefined;
function engine(foreign?: ForeignPhonemizer) {
    return makeNativeHindi(
        loadManifest<HindiDef>(import.meta.url, "chhattisgarhi.jsonc"),
        loadSharedPhonology(),
        foreign,
    );
}

/** Build the Chhattisgarhi phonemizer. `foreign` handles embedded Latin runs. */
export function createChhattisgarhi(foreign?: ForeignPhonemizer): { text(input: string): string } {
    return engine(foreign);
}

/** Bare word→IPA (tests). */
export function phonemizeWord(w: string): string {
    return (HNE ??= engine()).word(w);
}
