/**
 * Classical Nahuatl (nci) cardinal number → words. VIGESIMAL (base 20) and genuinely positional — hence
 * Pattern B. The traditional Spanish-based orthography with macrons is used, which nahuatl.ts phonemizes
 * directly (⟨ce⟩→[se], ⟨cu/hu⟩→[kʷ/w], ⟨tz tl⟩→[t͡s t͡ɬ], macron→length).
 *
 * SOURCE: English Wiktionary's Classical Nahuatl numeral data — `Module:number_list/data/nci` (which declares
 * `number_system = {id = "base20", power_base = 20}`) and Appendix:Classical Nahuatl numerals. That module is
 * the only machine-checkable full base-20 table available; it lemmatises 1–50 individually plus every round
 * value on the 20 / 400 / 8000 / 160 000 / 3 200 000 / 64 000 000 grid, and it gives long composites verbatim,
 * which is what pins the joining rules. The forms it uses are the standard Andrews/Karttunen ones (the repo's
 * Nahuatl g2p is authored from Andrews §2, but Andrews's orthography section does not tabulate the numerals,
 * so the numeral DATA is cited to Wiktionary rather than to Andrews).
 *
 * ★ THE POWERS OF TWENTY, each with its own noun:
 *     20⁰ —                20¹ pōhualli 'a count'      20² tzontli 'hair/tuft'   20³ xiquipilli 'bag'
 *     20⁴ pōhualxiquipilli   20⁵ tzonxiquipilli          20⁶ pōhualtzonxiquipilli
 *   Attested anchors this file reproduces EXACTLY: cempōhualli 20, centzontli 400, cenxiquipilli 8000,
 *   cempōhualxiquipilli 160 000, centzonxiquipilli 3 200 000, cempōhualtzonxiquipilli 64 000 000.
 *
 * ★★ TWO DIFFERENT JOINERS, and this is the crux:
 *   • Inside the sub-400 part the next word is prefixed with the linker ⟨on-⟩, which assimilates to ⟨om-⟩
 *     before a vowel or ⟨m⟩: cempōhualli oncē 21, cempōhualli omōme 22, cempōhualli ommahtlāctli 30,
 *     cempōhualli oncaxtōlli 35, caxtōlli onnāhui 19.
 *   • From 400 up the groups are joined by the relational word ⟨īpan⟩ 'on/upon it': centzontli īpan cē 401,
 *     centzontli īpan cempōhualli oncē 421, cenxiquipilli īpan centzontli īpan mahtlāctli oncē 8411.
 *   Verbatim long checks reproduced by this compositor: 9000 "cenxiquipilli īpan ōntzontli īpan
 *   mahtlācpōhualli", 15 000 "cenxiquipilli īpan caxtōlli omōntzontli īpan mahtlācpōhualli", 159 999
 *   "caxtōlli onnāuhxiquipilli īpan caxtōlli onnāuhtzontli īpan caxtōlli onnāppōhualli oncaxtōlli onnāhui",
 *   1 000 000 "chicuacempōhualxiquipilli īpan mācuīlxiquipilli".
 *
 * ★ 11–14 / 16–19 AND THEIR MULTIPLIER USE. There is no *11 word: 11 is mahtlāctli oncē (10+1) and 19 is
 *   caxtōlli onnāhui (15+4). The same additive shape is used when 11–19 MULTIPLIES a power: 220 is
 *   "mahtlāctli oncempōhualli" (10 scores + 1 score), 4400 "mahtlāctli oncentzontli", 104 000 "mahtlāctli
 *   omēxiquipilli". So a multiplier of 11–14 / 16–19 is emitted as ⟨mahtlāctli⟩/⟨caxtōlli⟩ + the residual
 *   multiplier bound to the magnitude noun — exactly what `magnitudeWords` builds.
 *
 * ATTESTED RANGE / FALLBACK: 1 … 1,279,999,999 (< 20⁷) is composed. 0–159,999 is densely attested (every
 * round value and several full composites); above 160,000 only the round anchors 160 000 / 200 000 /
 * 1 000 000 / 3 200 000 / 64 000 000 are attested — this compositor reproduces all five verbatim, and the
 * values between them are generated by the same positional rule (disclosed as generated, not attested).
 * At 20⁷ = 1,280,000,000 there is no further magnitude noun, so ≥ 20⁷ falls back to DIGIT-BY-DIGIT.
 *
 * VERIFIED: this compositor reproduces 212 of the 214 cardinal values the module lemmatises, exactly. The two
 * divergences are errors in the source, not here: at 580 it writes ⟨chiucnāppohualli⟩ (a dropped macron —
 * every other occurrence in the same file has ⟨chiucnāppōhualli⟩), and at 60 000 it gives "chicōnxiquipilli
 * īpan mācuīltzontli", which sums to 56 000 + 2 000 = 58 000; 60 000 needs ⟨mahtlāctzontli⟩ (4 000), which is
 * what this emits.
 *
 * ZERO: Classical Nahuatl has NO attested numeral for zero (Wiktionary lemmatises none). ⟨ahtle⟩ 'nothing'
 * is emitted so the engine renders "0" as something; it is a lexical stopgap, NOT an attested numeral.
 *
 * Variant spellings not used, for the record: ⟨ēi / yēi / yēyi⟩ for ēyi, ⟨chicuēi⟩ for chicuēyi, and the
 * unmacronised colonial ⟨cempoalli / matlactli / caxtulli⟩ shapes. Wiktionary's first-listed macronised
 * lemma is taken throughout, matching this engine's macron-aware g2p.
 */

const ZERO = "ahtle"; // 'nothing' — a stopgap, not an attested numeral (see the header)
// 1..9, then 10 and 15, the two additive bases inside a score.
const UNITS = ["", "cē", "ōme", "ēyi", "nāhui", "mācuīlli", "chicuacē", "chicōme", "chicuēyi", "chiucnāhui"];
const TEN = "mahtlāctli", FIFTEEN = "caxtōlli";

// The magnitude nouns for 20¹…20⁶. A name starting with ⟨p⟩ takes the LABIAL prefix series (cem-, ōm-, …);
// the others take the plain series (cen-, ōn-, …) — the same nine numerals, assimilated to the following stop.
const MAGNITUDES = ["", "pōhualli", "tzontli", "xiquipilli", "pōhualxiquipilli", "tzonxiquipilli", "pōhualtzonxiquipilli"];
// Multiplier combining forms 1..9, before a ⟨p⟩-initial magnitude: cempōhualli, ōmpōhualli, ēxpōhualli,
// nāppōhualli, mācuīlpōhualli, chicuacempōhualli, chicōmpōhualli, chicuēxpōhualli, chiucnāppōhualli.
const PRE_P = ["", "cem", "ōm", "ēx", "nāp", "mācuīl", "chicuacem", "chicōm", "chicuēx", "chiucnāp"];
// …and before ⟨t⟩/⟨x⟩: centzontli, ōntzontli, ētzontli, nāuhtzontli, mācuīltzontli, chicuacentzontli,
// chicōntzontli, chicuētzontli, chiucnāuhtzontli (identically for -xiquipilli).
const PRE_T = ["", "cen", "ōn", "ē", "nāuh", "mācuīl", "chicuacen", "chicōn", "chicuē", "chiucnāuh"];
// The 10 and 15 multiplier forms bind directly: mahtlācpōhualli 200, caxtōlpōhualli 300, mahtlāctzontli 4000,
// caxtōlxiquipilli 120000.
const PRE_10 = { p: "mahtlāc", t: "mahtlāc" }, PRE_15 = { p: "caxtōl", t: "caxtōl" };

/** The additive linker ⟨on-⟩, assimilating to ⟨om-⟩ before a vowel or ⟨m⟩ (omōme, omēyi, ommahtlāctli). */
function link(word: string): string {
    return (/^[aeiouāēīōū]/u.test(word) || word.startsWith("m") ? "om" : "on") + word;
}

/** Join a word list with the ⟨on-⟩ linker on every word after the first. */
function chain(words: string[]): string {
    return words[0] + words.slice(1).map((w) => " " + link(w)).join("");
}

/** A multiplier 1..19 bound to a magnitude noun (or to nothing, for the units place). */
function magnitudeWords(d: number, mag: string): string[] {
    if (mag === "") return d <= 9 ? [UNITS[d]!] : d === 10 ? [TEN] : d < 15 ? [TEN, UNITS[d - 10]!]
        : d === 15 ? [FIFTEEN] : [FIFTEEN, UNITS[d - 15]!];
    const P = mag.startsWith("p") ? PRE_P : PRE_T;
    const p10 = mag.startsWith("p") ? PRE_10.p : PRE_10.t, p15 = mag.startsWith("p") ? PRE_15.p : PRE_15.t;
    if (d <= 9) return [P[d]! + mag];
    if (d === 10) return [p10 + mag];
    if (d < 15) return [TEN, P[d - 10]! + mag]; // 220 = mahtlāctli oncempōhualli
    if (d === 15) return [p15 + mag];
    return [FIFTEEN, P[d - 15]! + mag]; // 380 = caxtōlli onnāppōhualli
}

/** Non-negative integer → Classical Nahuatl words. ≥ 20⁷ (no further magnitude noun) → digit-by-digit. */
export function numberToWords(n: number): string {
    if (!Number.isSafeInteger(n) || n < 0 || n >= 20 ** 7) {
        return [...String(Math.abs(n))].filter((c) => c >= "0" && c <= "9")
            .map((d) => (d === "0" ? ZERO : UNITS[Number(d)]!)).join(" ");
    }
    if (n === 0) return ZERO;
    // The base-20 digits, most significant first. Powers 20⁶…20² each become their own ⟨īpan⟩ group; the
    // 20¹ and 20⁰ places form the single sub-400 chunk that uses the ⟨on-⟩ linker instead.
    const groups: string[] = [];
    let rest = n;
    for (let k = 6; k >= 2; k--) {
        const p = 20 ** k, d = Math.floor(rest / p);
        if (d > 0) groups.push(chain(magnitudeWords(d, MAGNITUDES[k]!)));
        rest -= d * p;
    }
    const score = Math.floor(rest / 20), unit = rest % 20;
    const tail = [...(score ? magnitudeWords(score, MAGNITUDES[1]!) : []), ...(unit ? magnitudeWords(unit, "") : [])];
    if (tail.length) groups.push(chain(tail));
    return groups.join(" īpan ");
}
